/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_step_definition_token1 = 1,
  anon_sym_PIPE = 2,
  aux_sym_table_header_name_token1 = 3,
  anon_sym_PIPE_LF = 4,
  sym_table_cell = 5,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 6,
  sym_docstring_line = 7,
  sym_tag = 8,
  sym_section_keyword = 9,
  sym_comment = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_quoted_string_token1 = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_quoted_string_token2 = 14,
  anon_sym_BQUOTE = 15,
  aux_sym_quoted_string_token3 = 16,
  sym_number = 17,
  sym_reference = 18,
  sym__text = 19,
  sym__space = 20,
  sym_source_file = 21,
  sym_feature = 22,
  sym_section = 23,
  sym_step = 24,
  sym_step_definition = 25,
  sym_table = 26,
  sym_table_header = 27,
  sym_table_header_name = 28,
  sym_table_row = 29,
  sym_docstring = 30,
  sym_docstring_start = 31,
  sym_docstring_end = 32,
  sym_docstring_lang = 33,
  sym_docstring_content = 34,
  aux_sym__tags = 35,
  sym_step_keywords = 36,
  sym_title = 37,
  sym_summary = 38,
  sym_summary_line = 39,
  sym_quoted_string = 40,
  aux_sym_feature_repeat1 = 41,
  aux_sym_section_repeat1 = 42,
  aux_sym_step_definition_repeat1 = 43,
  aux_sym_table_repeat1 = 44,
  aux_sym_table_header_repeat1 = 45,
  aux_sym_table_row_repeat1 = 46,
  aux_sym_docstring_content_repeat1 = 47,
  aux_sym_summary_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_step_definition_token1] = "step_definition_token1",
  [anon_sym_PIPE] = "|",
  [aux_sym_table_header_name_token1] = "table_header_name_token1",
  [anon_sym_PIPE_LF] = "|\n",
  [sym_table_cell] = "table_cell",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [sym_docstring_line] = "docstring_line",
  [sym_tag] = "tag",
  [sym_section_keyword] = "section_keyword",
  [sym_comment] = "comment",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_string_token2] = "quoted_string_token2",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_quoted_string_token3] = "quoted_string_token3",
  [sym_number] = "number",
  [sym_reference] = "reference",
  [sym__text] = "_text",
  [sym__space] = "_space",
  [sym_source_file] = "source_file",
  [sym_feature] = "feature",
  [sym_section] = "section",
  [sym_step] = "step",
  [sym_step_definition] = "step_definition",
  [sym_table] = "table",
  [sym_table_header] = "table_header",
  [sym_table_header_name] = "table_header_name",
  [sym_table_row] = "table_row",
  [sym_docstring] = "docstring",
  [sym_docstring_start] = "docstring_start",
  [sym_docstring_end] = "docstring_end",
  [sym_docstring_lang] = "docstring_lang",
  [sym_docstring_content] = "docstring_content",
  [aux_sym__tags] = "_tags",
  [sym_step_keywords] = "step_keywords",
  [sym_title] = "title",
  [sym_summary] = "summary",
  [sym_summary_line] = "summary_line",
  [sym_quoted_string] = "quoted_string",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_step_definition_repeat1] = "step_definition_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_table_header_repeat1] = "table_header_repeat1",
  [aux_sym_table_row_repeat1] = "table_row_repeat1",
  [aux_sym_docstring_content_repeat1] = "docstring_content_repeat1",
  [aux_sym_summary_repeat1] = "summary_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_step_definition_token1] = aux_sym_step_definition_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_table_header_name_token1] = aux_sym_table_header_name_token1,
  [anon_sym_PIPE_LF] = anon_sym_PIPE_LF,
  [sym_table_cell] = sym_table_cell,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [sym_docstring_line] = sym_docstring_line,
  [sym_tag] = sym_tag,
  [sym_section_keyword] = sym_section_keyword,
  [sym_comment] = sym_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_string_token2] = aux_sym_quoted_string_token2,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_quoted_string_token3] = aux_sym_quoted_string_token3,
  [sym_number] = sym_number,
  [sym_reference] = sym_reference,
  [sym__text] = sym__text,
  [sym__space] = sym__space,
  [sym_source_file] = sym_source_file,
  [sym_feature] = sym_feature,
  [sym_section] = sym_section,
  [sym_step] = sym_step,
  [sym_step_definition] = sym_step_definition,
  [sym_table] = sym_table,
  [sym_table_header] = sym_table_header,
  [sym_table_header_name] = sym_table_header_name,
  [sym_table_row] = sym_table_row,
  [sym_docstring] = sym_docstring,
  [sym_docstring_start] = sym_docstring_start,
  [sym_docstring_end] = sym_docstring_end,
  [sym_docstring_lang] = sym_docstring_lang,
  [sym_docstring_content] = sym_docstring_content,
  [aux_sym__tags] = aux_sym__tags,
  [sym_step_keywords] = sym_step_keywords,
  [sym_title] = sym_title,
  [sym_summary] = sym_summary,
  [sym_summary_line] = sym_summary_line,
  [sym_quoted_string] = sym_quoted_string,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_step_definition_repeat1] = aux_sym_step_definition_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_table_header_repeat1] = aux_sym_table_header_repeat1,
  [aux_sym_table_row_repeat1] = aux_sym_table_row_repeat1,
  [aux_sym_docstring_content_repeat1] = aux_sym_docstring_content_repeat1,
  [aux_sym_summary_repeat1] = aux_sym_summary_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_step_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_table_header_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_table_cell] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_docstring_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_section_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_header] = {
    .visible = true,
    .named = true,
  },
  [sym_table_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_table_row] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring_start] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring_end] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring_lang] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__tags] = {
    .visible = false,
    .named = false,
  },
  [sym_step_keywords] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_summary] = {
    .visible = true,
    .named = true,
  },
  [sym_summary_line] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_step_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_row_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_docstring_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_summary_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 12,
  [37] = 16,
  [38] = 35,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 40,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 33,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(55);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '`') ADVANCE(58);
      if (lookahead == '|') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(55);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '`') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '#') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '#') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '#') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '#') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '@') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == '#') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '|') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '@') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      END_STATE();
    case 12:
      if (lookahead == '#') ADVANCE(48);
      if (lookahead == '<') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '>') ADVANCE(54);
      END_STATE();
    case 13:
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == '<') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '`') ADVANCE(60);
      END_STATE();
    case 14:
      if (lookahead == '#') ADVANCE(50);
      if (lookahead == '<') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 15:
      if (lookahead == '#') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '@') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(17);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '|') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '\'') ADVANCE(55);
      if (lookahead == '`') ADVANCE(58);
      if (lookahead == '|') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_step_definition_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_step_definition_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_step_definition_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_step_definition_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_step_definition_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(17);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '\n') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_table_header_name_token1);
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead == ':') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_table_header_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_table_header_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PIPE_LF);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') ADVANCE(37);
      if (lookahead == '|') ADVANCE(51);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_table_cell);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_docstring_line);
      if (lookahead == '\n') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_docstring_line);
      if (lookahead == '"') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_docstring_line);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_docstring_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '@') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '@') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_section_keyword);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_section_keyword);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '"' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(51);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '`') ADVANCE(51);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\'' ||
          lookahead == '<' ||
          lookahead == '>') ADVANCE(51);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_quoted_string_token3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '`') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_quoted_string_token3);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '`') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_reference);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\n') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == ':') ADVANCE(47);
      if (lookahead == '@') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '@') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == ':') ADVANCE(47);
      if (lookahead == ' ' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '@') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(70);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == '@') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(71);
      if (lookahead == ':') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '@') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__space);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 21},
  [3] = {.lex_state = 21},
  [4] = {.lex_state = 21},
  [5] = {.lex_state = 21},
  [6] = {.lex_state = 21},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 21},
  [13] = {.lex_state = 21},
  [14] = {.lex_state = 21},
  [15] = {.lex_state = 21},
  [16] = {.lex_state = 21},
  [17] = {.lex_state = 21},
  [18] = {.lex_state = 21},
  [19] = {.lex_state = 21},
  [20] = {.lex_state = 21},
  [21] = {.lex_state = 21},
  [22] = {.lex_state = 21},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 21},
  [26] = {.lex_state = 21},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 21},
  [30] = {.lex_state = 21},
  [31] = {.lex_state = 22},
  [32] = {.lex_state = 22},
  [33] = {.lex_state = 21},
  [34] = {.lex_state = 21},
  [35] = {.lex_state = 22},
  [36] = {.lex_state = 22},
  [37] = {.lex_state = 22},
  [38] = {.lex_state = 22},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 22},
  [46] = {.lex_state = 21},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 21},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 22},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 22},
  [62] = {.lex_state = 11},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 22},
  [66] = {.lex_state = 22},
  [67] = {.lex_state = 22},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 22},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 22},
  [74] = {.lex_state = 22},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 22},
  [77] = {.lex_state = 22},
  [78] = {.lex_state = 15},
  [79] = {.lex_state = 22},
  [80] = {.lex_state = 22},
  [81] = {.lex_state = 22},
  [82] = {.lex_state = 22},
  [83] = {.lex_state = 22},
  [84] = {.lex_state = 22},
  [85] = {.lex_state = 22},
  [86] = {.lex_state = 22},
  [87] = {.lex_state = 22},
  [88] = {.lex_state = 22},
  [89] = {.lex_state = 22},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_step_definition_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
    [sym__space] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(74),
    [sym_feature] = STATE(67),
    [aux_sym__tags] = STATE(52),
    [sym_tag] = ACTIONS(5),
    [sym_section_keyword] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym__space] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      aux_sym_table_header_name_token1,
    ACTIONS(19), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(38), 1,
      sym_table_header,
    STATE(48), 1,
      sym_docstring_start,
    STATE(83), 2,
      sym_table,
      sym_docstring,
    ACTIONS(13), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [31] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(35), 1,
      sym_table_header,
    STATE(51), 1,
      sym_table,
    STATE(17), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [62] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(35), 1,
      sym_table_header,
    STATE(47), 1,
      sym_table,
    STATE(13), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [93] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(35), 1,
      sym_table_header,
    STATE(43), 1,
      sym_table,
    STATE(15), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [124] = 9,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(35), 1,
      sym_table_header,
    STATE(46), 1,
      sym_table,
    STATE(18), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [155] = 8,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(39), 1,
      sym_reference,
    STATE(82), 1,
      sym_step_definition,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
    ACTIONS(31), 2,
      aux_sym_step_definition_token1,
      sym_number,
    STATE(10), 2,
      sym_quoted_string,
      aux_sym_step_definition_repeat1,
  [183] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_tag,
    ACTIONS(43), 1,
      sym_section_keyword,
    ACTIONS(45), 1,
      sym__text,
    STATE(26), 1,
      sym_summary,
    STATE(27), 1,
      aux_sym_summary_repeat1,
    STATE(62), 1,
      aux_sym__tags,
    STATE(89), 1,
      sym_summary_line,
    STATE(20), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [215] = 10,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_tag,
    ACTIONS(43), 1,
      sym_section_keyword,
    ACTIONS(45), 1,
      sym__text,
    STATE(27), 1,
      aux_sym_summary_repeat1,
    STATE(29), 1,
      sym_summary,
    STATE(62), 1,
      aux_sym__tags,
    STATE(89), 1,
      sym_summary_line,
    STATE(19), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [247] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_BQUOTE,
    ACTIONS(49), 1,
      sym_reference,
    ACTIONS(51), 1,
      sym__space,
    ACTIONS(47), 2,
      aux_sym_step_definition_token1,
      sym_number,
    STATE(11), 2,
      sym_quoted_string,
      aux_sym_step_definition_repeat1,
  [274] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_SQUOTE,
    ACTIONS(62), 1,
      anon_sym_BQUOTE,
    ACTIONS(65), 1,
      sym_reference,
    ACTIONS(68), 1,
      sym__space,
    ACTIONS(53), 2,
      aux_sym_step_definition_token1,
      sym_number,
    STATE(11), 2,
      sym_quoted_string,
      aux_sym_step_definition_repeat1,
  [301] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_table_row_repeat1,
    STATE(16), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    ACTIONS(70), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [323] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(14), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [345] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(76), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(14), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [367] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(14), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [389] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_table_row_repeat1,
    STATE(16), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    ACTIONS(79), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [411] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(14), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [433] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(23), 1,
      aux_sym_table_header_name_token1,
    STATE(7), 1,
      sym_step_keywords,
    STATE(14), 2,
      sym_step,
      aux_sym_section_repeat1,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [455] = 7,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      sym_tag,
    ACTIONS(90), 1,
      sym_section_keyword,
    STATE(62), 1,
      aux_sym__tags,
    STATE(22), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [478] = 7,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_tag,
    ACTIONS(90), 1,
      sym_section_keyword,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      aux_sym__tags,
    STATE(22), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [501] = 7,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_tag,
    ACTIONS(90), 1,
      sym_section_keyword,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      aux_sym__tags,
    STATE(22), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [524] = 7,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      sym_tag,
    ACTIONS(101), 1,
      sym_section_keyword,
    STATE(62), 1,
      aux_sym__tags,
    STATE(22), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [547] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
    ACTIONS(104), 2,
      aux_sym_step_definition_token1,
      sym_number,
    ACTIONS(106), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_reference,
  [562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 3,
      aux_sym_step_definition_token1,
      sym_number,
      sym__space,
    ACTIONS(110), 4,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_reference,
  [577] = 7,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_tag,
    ACTIONS(90), 1,
      sym_section_keyword,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      aux_sym__tags,
    STATE(22), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [600] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_tag,
    ACTIONS(90), 1,
      sym_section_keyword,
    STATE(62), 1,
      aux_sym__tags,
    STATE(21), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [620] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym__text,
    STATE(28), 1,
      aux_sym_summary_repeat1,
    STATE(89), 1,
      sym_summary_line,
    ACTIONS(114), 2,
      sym_tag,
      sym_section_keyword,
  [640] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym__text,
    STATE(28), 1,
      aux_sym_summary_repeat1,
    STATE(89), 1,
      sym_summary_line,
    ACTIONS(116), 2,
      sym_tag,
      sym_section_keyword,
  [660] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_tag,
    ACTIONS(90), 1,
      sym_section_keyword,
    STATE(62), 1,
      aux_sym__tags,
    STATE(25), 2,
      sym_section,
      aux_sym_feature_repeat1,
  [680] = 6,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(5), 1,
      sym_tag,
    ACTIONS(7), 1,
      sym_section_keyword,
    ACTIONS(9), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym__tags,
    STATE(69), 1,
      sym_feature,
  [699] = 5,
    ACTIONS(121), 1,
      anon_sym_PIPE,
    ACTIONS(123), 1,
      aux_sym_table_header_name_token1,
    STATE(32), 1,
      aux_sym_table_header_repeat1,
    STATE(66), 1,
      sym_table_header_name,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [716] = 5,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(127), 1,
      aux_sym_table_header_name_token1,
    STATE(32), 1,
      aux_sym_table_header_repeat1,
    STATE(66), 1,
      sym_table_header_name,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [733] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_tag,
      sym_section_keyword,
  [746] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(134), 1,
      aux_sym_table_header_name_token1,
    ACTIONS(132), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [761] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
    STATE(12), 2,
      sym_table_row,
      aux_sym_table_repeat1,
  [776] = 5,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym__space,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    STATE(40), 1,
      aux_sym_table_row_repeat1,
    STATE(37), 2,
      sym_table_row,
      aux_sym_table_repeat1,
  [793] = 5,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__space,
    ACTIONS(81), 1,
      anon_sym_PIPE,
    STATE(40), 1,
      aux_sym_table_row_repeat1,
    STATE(37), 2,
      sym_table_row,
      aux_sym_table_repeat1,
  [810] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    STATE(40), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
    STATE(36), 2,
      sym_table_row,
      aux_sym_table_repeat1,
  [825] = 4,
    ACTIONS(136), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(138), 1,
      sym_docstring_line,
    STATE(49), 1,
      aux_sym_docstring_content_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [839] = 4,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_PIPE_LF,
    STATE(44), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [853] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(116), 3,
      sym_tag,
      sym_section_keyword,
      sym__text,
  [865] = 4,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(144), 1,
      anon_sym_PIPE_LF,
    STATE(44), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [879] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [891] = 4,
    ACTIONS(146), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_PIPE_LF,
    STATE(44), 1,
      aux_sym_table_row_repeat1,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [905] = 4,
    ACTIONS(123), 1,
      aux_sym_table_header_name_token1,
    STATE(31), 1,
      aux_sym_table_header_repeat1,
    STATE(66), 1,
      sym_table_header_name,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [919] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [931] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [943] = 4,
    ACTIONS(151), 1,
      sym_docstring_line,
    STATE(39), 1,
      aux_sym_docstring_content_repeat1,
    STATE(61), 1,
      sym_docstring_content,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [957] = 4,
    ACTIONS(153), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(155), 1,
      sym_docstring_line,
    STATE(49), 1,
      aux_sym_docstring_content_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [971] = 4,
    ACTIONS(158), 1,
      aux_sym_table_header_name_token1,
    ACTIONS(160), 1,
      sym_docstring_line,
    STATE(72), 1,
      sym_docstring_lang,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [985] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      sym_tag,
      sym_section_keyword,
  [997] = 4,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_tag,
    ACTIONS(164), 1,
      sym__space,
    STATE(58), 1,
      aux_sym__tags,
  [1010] = 3,
    ACTIONS(166), 1,
      aux_sym_quoted_string_token1,
    ACTIONS(168), 1,
      sym_reference,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [1021] = 3,
    ACTIONS(170), 1,
      aux_sym_quoted_string_token3,
    ACTIONS(172), 1,
      sym_reference,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [1032] = 2,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
    ACTIONS(125), 2,
      anon_sym_PIPE,
      aux_sym_table_header_name_token1,
  [1041] = 3,
    ACTIONS(174), 1,
      aux_sym_quoted_string_token2,
    ACTIONS(176), 1,
      sym_reference,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [1052] = 3,
    ACTIONS(149), 1,
      anon_sym_PIPE_LF,
    ACTIONS(178), 1,
      anon_sym_PIPE,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1063] = 4,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_tag,
    ACTIONS(183), 1,
      sym__space,
    STATE(58), 1,
      aux_sym__tags,
  [1076] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__text,
    STATE(81), 1,
      sym_title,
  [1089] = 4,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__text,
    ACTIONS(187), 1,
      sym__space,
    STATE(80), 1,
      sym_title,
  [1102] = 3,
    ACTIONS(189), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(86), 1,
      sym_docstring_end,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1113] = 4,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_tag,
    ACTIONS(191), 1,
      sym__space,
    STATE(58), 1,
      aux_sym__tags,
  [1126] = 4,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__text,
    STATE(84), 1,
      sym_title,
  [1139] = 4,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__text,
    ACTIONS(193), 1,
      sym__space,
    STATE(79), 1,
      sym_title,
  [1152] = 2,
    ACTIONS(195), 1,
      anon_sym_PIPE,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1160] = 2,
    ACTIONS(197), 1,
      anon_sym_PIPE,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1168] = 2,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1176] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_section_keyword,
  [1186] = 2,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1194] = 3,
    ACTIONS(3), 1,
      sym__space,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_section_keyword,
  [1204] = 2,
    ACTIONS(207), 1,
      sym_docstring_line,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [1212] = 2,
    ACTIONS(209), 1,
      sym_docstring_line,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [1220] = 2,
    ACTIONS(211), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1228] = 2,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1236] = 2,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1244] = 2,
    ACTIONS(211), 1,
      anon_sym_SQUOTE,
    ACTIONS(9), 2,
      sym_comment,
      sym__space,
  [1252] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_PIPE,
      sym__space,
  [1260] = 2,
    ACTIONS(215), 1,
      sym_table_cell,
    ACTIONS(3), 2,
      sym_comment,
      sym__space,
  [1268] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym__space,
  [1275] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym__space,
  [1282] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym__space,
  [1289] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym__space,
  [1296] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym__space,
  [1303] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym__space,
  [1310] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym__space,
  [1317] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym__space,
  [1324] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__space,
  [1331] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym__space,
  [1338] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym__space,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 155,
  [SMALL_STATE(8)] = 183,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 247,
  [SMALL_STATE(11)] = 274,
  [SMALL_STATE(12)] = 301,
  [SMALL_STATE(13)] = 323,
  [SMALL_STATE(14)] = 345,
  [SMALL_STATE(15)] = 367,
  [SMALL_STATE(16)] = 389,
  [SMALL_STATE(17)] = 411,
  [SMALL_STATE(18)] = 433,
  [SMALL_STATE(19)] = 455,
  [SMALL_STATE(20)] = 478,
  [SMALL_STATE(21)] = 501,
  [SMALL_STATE(22)] = 524,
  [SMALL_STATE(23)] = 547,
  [SMALL_STATE(24)] = 562,
  [SMALL_STATE(25)] = 577,
  [SMALL_STATE(26)] = 600,
  [SMALL_STATE(27)] = 620,
  [SMALL_STATE(28)] = 640,
  [SMALL_STATE(29)] = 660,
  [SMALL_STATE(30)] = 680,
  [SMALL_STATE(31)] = 699,
  [SMALL_STATE(32)] = 716,
  [SMALL_STATE(33)] = 733,
  [SMALL_STATE(34)] = 746,
  [SMALL_STATE(35)] = 761,
  [SMALL_STATE(36)] = 776,
  [SMALL_STATE(37)] = 793,
  [SMALL_STATE(38)] = 810,
  [SMALL_STATE(39)] = 825,
  [SMALL_STATE(40)] = 839,
  [SMALL_STATE(41)] = 853,
  [SMALL_STATE(42)] = 865,
  [SMALL_STATE(43)] = 879,
  [SMALL_STATE(44)] = 891,
  [SMALL_STATE(45)] = 905,
  [SMALL_STATE(46)] = 919,
  [SMALL_STATE(47)] = 931,
  [SMALL_STATE(48)] = 943,
  [SMALL_STATE(49)] = 957,
  [SMALL_STATE(50)] = 971,
  [SMALL_STATE(51)] = 985,
  [SMALL_STATE(52)] = 997,
  [SMALL_STATE(53)] = 1010,
  [SMALL_STATE(54)] = 1021,
  [SMALL_STATE(55)] = 1032,
  [SMALL_STATE(56)] = 1041,
  [SMALL_STATE(57)] = 1052,
  [SMALL_STATE(58)] = 1063,
  [SMALL_STATE(59)] = 1076,
  [SMALL_STATE(60)] = 1089,
  [SMALL_STATE(61)] = 1102,
  [SMALL_STATE(62)] = 1113,
  [SMALL_STATE(63)] = 1126,
  [SMALL_STATE(64)] = 1139,
  [SMALL_STATE(65)] = 1152,
  [SMALL_STATE(66)] = 1160,
  [SMALL_STATE(67)] = 1168,
  [SMALL_STATE(68)] = 1176,
  [SMALL_STATE(69)] = 1186,
  [SMALL_STATE(70)] = 1194,
  [SMALL_STATE(71)] = 1204,
  [SMALL_STATE(72)] = 1212,
  [SMALL_STATE(73)] = 1220,
  [SMALL_STATE(74)] = 1228,
  [SMALL_STATE(75)] = 1236,
  [SMALL_STATE(76)] = 1244,
  [SMALL_STATE(77)] = 1252,
  [SMALL_STATE(78)] = 1260,
  [SMALL_STATE(79)] = 1268,
  [SMALL_STATE(80)] = 1275,
  [SMALL_STATE(81)] = 1282,
  [SMALL_STATE(82)] = 1289,
  [SMALL_STATE(83)] = 1296,
  [SMALL_STATE(84)] = 1303,
  [SMALL_STATE(85)] = 1310,
  [SMALL_STATE(86)] = 1317,
  [SMALL_STATE(87)] = 1324,
  [SMALL_STATE(88)] = 1331,
  [SMALL_STATE(89)] = 1338,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_definition, 1, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_step_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_step_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_step_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_step_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_step_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_step_definition_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 6, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 7, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_keywords, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_keywords, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_summary, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_summary_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_summary_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_header, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_header_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_header_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 5, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step, 5, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_docstring_content, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_docstring_content_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_docstring_content_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_docstring_start, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__tags, 2, 0, 0), SHIFT_REPEAT(58),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__tags, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_header_name, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_docstring_lang, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_docstring_start, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docstring, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_summary_line, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docstring_end, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gherkin(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gherkin",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 2,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
